### PR TITLE
Update client.rb

### PR DESCRIPTION
**Pull request by xorgnak**
fix for broken client initializer.

### CODE REVIEW

**Comment by andreibondarev** [comment]
@xorgnak Great find, thank you!

**Comment by andreibondarev** [comment]
@xorgnak I just pushed a new gem version out. Would you mind bumping it up in the https://github.com/andreibondarev/langchainrb gem as well if it's not too difficult? Thanks!

**Comment by andreibondarev** [comment]
@xorgnak Sorry -- could you please explain how this broke the client initializer?

**Comment by xorgnak** [comment]
Passing a bare hash key to the initializer returned the keys' value on a nil hash.

I just pushed a *working* version to my fork. The only change was to initialize the class with an explicit hash and strip the api_key argument.  Seems to be working for me.

I'm moving on to the langchainrb issue next. I'm thinking this fix takes care of both issues. Stay tuned.

**Pull request merged**
