### PR TITLE
v2 endpoint

### PR DESCRIPTION
**Pull request by ScotterC**
Here's the [changelog](https://docs.cohere.com/v2/docs/migrating-v1-to-v2) on Cohere's side:

> model is a required field for Embed, Rerank, Classify, and Chat.
> embedding_types is a required field for Embed.

For Chat there are a bunch of changes in message/response structure

### CODE REVIEW

**Comment by andreibondarev** [comment]
@ScotterC I didn't realize there's a v2 endpoint! Why'd you close it?

**Comment by ScotterC** [comment]
@andreibondarev  ha, cause I only looked into `rerank` endpoint and I had no idea how it might impact others. this PR was meant for my own fork to just test. Good news is the swap works just fine for rerank

**Comment by ScotterC** [comment]
Re opening since I'm moving forward with using this branch of mine and tests pass locally. Will add to it if other aspects come up. I have not directly tried endpoints other than rerank thoguh

**Comment by ScotterC** [comment]
Sounds good to me. A major version bump works as well. Thanks for all the updates!

**Pull request merged**
