### PR TITLE
Add support request timeout

### PR DESCRIPTION
**Pull request by naoa**
I'd like to set request timeout of Faraday.

### CODE REVIEW

**Comment by andreibondarev** [comment]
@naoa Please upmerge.

**Comment by andreibondarev** [comment]
Is it the linter? Do you need to run `standardrb --fix`?

**Comment by naoa** [comment]
I've rebased.

It appears that changes to the Cohere::Client initializer have made it impossible to instantiate it as shown below. I've updated the specs to reflect this change, but I wonder if it would still be desirable to allow instantiation with named arguments like api_key:?

```ruby
def initialize(api_key, timeout: nil) 
```

* NG case
```
client = Cohere::Client.new(
  api_key: ENV['COHERE_API_KEY']
)
``` 

* Valid case
```
client = Cohere::Client.new(
  ENV['COHERE_API_KEY']
)
```

**Comment by andreibondarev** [comment]
@naoa Yeah, I would prefer keyword args: `def initialize(api_key:, timeout: nil) `

**Comment by naoa** [comment]
I've changed the initializer to keyword args style.
And also changed readme.
Note: This is a backward incompatibility change.

**Pull request merged**
